language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - node
  - '6.4.0'
after_success:
  - npm run coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
